theme: just-the-docs
title: Orange Robotics
description: My personal blog, to share the technologies that fascinate me.

# Make the source folder /docs instead of root
source: docs

# Highlight important messages
callouts:
  note-title:
    color: purple
  tip:
    color: green
  tldr:
    color: green
    title: tl;dr
  important:
    color: blue
    title: Important
  warning:
    color: red
    title: Warning

# Include tokens to prove ownership of the site
include: [".well-known"]
