remote_theme: pmarsceill/just-the-docs
title: Orange Robotics
description: My personal blog, to share the technologies that fascinate me.
color_scheme: dark

callouts:
  note-title:
    title: Note
    color: purple