remote_theme: pmarsceill/just-the-docs
theme: just-the-docs
title: Orange Robotics
description: My personal blog, to share the technologies that fascinate me.
color_scheme: dark

callouts:
  note-title:
    color: purple
  tip:
    color: green
  important:
    color: blue
    title: Important
  

include: [".well-known"]